tracks:

  release:
    key:
    applicableGameVersion: '2026.01.21.0000.0000'
    runtimeVersion: 10.0.0
    hidden: false
    displayName: "Stable"
    description: "Released, stable versions of Dalamud (default branch)"

  canary:
    key:
    applicableGameVersion: '2026.01.21.0000.0000'
    runtimeVersion: 10.0.0
    hidden: true
    displayName: "Canary"
    description: "Prerelease track"

  stg:
    key: "Carbonara"
    applicableGameVersion: '2026.01.21.0000.0000'
    runtimeVersion: 10.0.0
    hidden: false
    displayName: "Beta Testing"
    description: "Prerelease version of Dalamud for Patch 7.4. MAY CAUSE CRASHES, report problems in Discord!"
