tracks:

  release:
    key:
    applicableGameVersion: '2025.10.30.0000.0000'
    runtimeVersion: 9.0.3
    hidden: false
    displayName: "Stable"
    description: "Released, stable versions of Dalamud (default branch)"

  canary:
    key:
    applicableGameVersion: '2025.10.30.0000.0000'
    runtimeVersion: 9.0.3
    hidden: true
    displayName: "Canary"
    description: "Prerelease track"

  stg:
    key: "Rigatoni al Segreta"
    applicableGameVersion: '2025.10.30.0000.0000'
    runtimeVersion: 9.0.3
    hidden: false
    displayName: "Beta Testing"
    description: "Early testing of Dalamud for patches, may contain new features"

  api14:
    key: "FUTURE"
    applicableGameVersion: '2025.10.30.0000.0000'
    runtimeVersion: 10.0.0
    hidden: false
    displayName: "api14 / .NET10"
    description: "[NOT FOR PATCH BETA] Next major Dalamud version, .NET 10 upgrade"
