tracks:

  release:
    key:
    applicableGameVersion: '2025.10.30.0000.0000'
    runtimeVersion: 10.0.0
    hidden: false
    displayName: "Stable"
    description: "Released, stable versions of Dalamud (default branch)"

  canary:
    key:
    applicableGameVersion: '2025.10.30.0000.0000'
    runtimeVersion: 10.0.0
    hidden: true
    displayName: "Canary"
    description: "Prerelease track"

  stg:
    key: "Carbonara"
    applicableGameVersion: '2025.12.18.0000.0000'
    runtimeVersion: 10.0.0
    hidden: true
    displayName: "Beta Testing"
    description: "Early testing of Dalamud for patches, may contain new features"
