tracks:

  release:
    key:
    applicableGameVersion: '2025.10.13.0000.0000'
    runtimeVersion: 9.0.3
    hidden: false
    displayName: "Stable"
    description: "Released, stable versions of Dalamud (default branch)"

  canary:
    key:
    applicableGameVersion: '2025.10.13.0000.0000'
    runtimeVersion: 9.0.3
    hidden: true
    displayName: "Canary"
    description: "Prerelease track"

  stg:
    key: "Rigatoni al Segreto"
    applicableGameVersion: '2025.10.13.0000.0000'
    runtimeVersion: 9.0.3
    hidden: false
    displayName: "Testing"
    description: "Early testing of Dalamud for patches, may contain new features"

  api13:
    key: "don't actually use this"
    applicableGameVersion: '2025.08.00.0000.0000'
    runtimeVersion: 9.0.3
    hidden: true
    displayName: "Developer Preview"
    description: "Early developer-only testing, expect crashes and critical issues"
